### ISSUE TITLE
Wrong Parameters in request: ret=PARAM NG"

### ISSUE THREAD

**Issue by maggiagg** [yankee42/node-red-contrib-daikin-ac#3]
I get this error when trying to change targettemperature

"Error calling setACControlInfo("{\"targetTemperature\":18}"): Wrong Parameters in request: ret=PARAM NG"

Requests to get information seem to work ok.

**Comment by yankee42** [comment]
Are you using the option `useGetToPost`? Please try to toggle it. It is in the configuration node next the adapter address.

**Comment by maggiagg** [comment]
That did the trick.  Do you need help in making documentation for the node?

Thanks for a great node!

REgards
Magnus

**Comment by yankee42** [comment]
> That did the trick. Do you need help in making documentation for the node?

Since this is just a wrapper for the [daikin-controller](https://github.com/Apollon77/daikin-controller) library I feel that only documentation needed is about the specialties of the wrapper. However if there is anything you feel should be mentioned in the docs here, any suggestions/pull requests are welcome.
